[package]
name = "age-of-empires"
version = "0.1.0"
authors = ["Nick <nicholas.spain96@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.13.2"

[features]
default = ["vulkan"]

empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
